[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mango-panel"
version = "0.1.0"
description = "MangoPanel translates your manga automagically"
readme = "README.md"
authors = [
    { name = "Jan Borowski", email = "s31890@pjwstk.edu.pl" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "langchain",
    "langgraph",
    "paddlepaddle-gpu==3.0.0",
    "paddleocr[all]",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pip]
index-url = "https://www.paddlepaddle.org.cn/packages/stable/cu126/"
extra-index-url = "https://pypi.org/simple/"
trusted-host = ["www.paddlepaddle.org.cn"]

[[tool.uv.index]]
url = "https://www.paddlepaddle.org.cn/packages/stable/cu126/"
default = true

[[tool.uv.index]]
url = "https://pypi.org/simple/"

